services:
  catalogue:
 #  dockerfile: catalogue.dockerfile
    build: ./catalogue:1.0.0
  #  image: catalogue:1.0.0
    container_name: catalogue
    depends_on:
      - mongodb

  user:
   # image: talarisureshdevops/user:1.0.0
    build: ./user:1.0.0
    container_name: user
    depends_on:
      - redis
      - mongodb

  cart:
   # image: talarisureshdevops/cart:1.0.0
    build: ./cart:1.0.0
    container_name: cart
    depends_on:
      - redis
      - catalogue

  shipping:
  # image: talarisureshdevops/shipping:1.0.0
    build: ./shipping:1.0.0
    container_name: shipping
    depends_on:
      - mysql
      - cart

  payment:
  #  image: talarisureshdevops/payment:1.0.0
    build: ./payment:1.0.0
    container_name: payment
    environment:
      CART_HOST: "cart"
      CART_PORT: "8080"
      USER_HOST: "user"
      USER_PORT: "8080"
      AMQP_HOST: "rabbitmq"
      AMQP_USER: "roboshop"
      AMQP_PASS: "roboshop123"
    depends_on:
      - rabbitmq
      - cart
      - user

  frontend:
  #  image: talarisureshdevops/frontend:1.0.0
    build: ./frontend:1.0.0
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - payment

  mongodb:
  #  image: talarisureshdevops/mongodb:1.0.0
    build: ./mongodb:1.0.0
    container_name: mongodb

  redis:
    image: redis:7.0
    container_name: redis

  mysql:
    image: ./mysql:1.0.0
    container_name: mysql

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123

networks:
  default:
    name: roboshop