services:
  catalogue:
    build: 
      context: .
      dockerfile: catalogue.dockerfile
    image: talarisureshdevops/catalogue:1.0.0
    container_name: catalogue
    depends_on:
      - mongodb
  mongodb:
      build:
        context: .
        dockerfile: mongodb.dockerfile
      image: talarisureshdevops/mongodb:1.0.0
      container_name: mongodb

  frontend:
    build: 
      context: .
      dockerfile: frontend.dockerfile
    image: talarisureshdevops/frontend:1.0.0
    container_name: frontend
    depends_on:
      - catalogue
      
networks:
  default:
    driver: bridge
    name: roboshop
      

